import { z } from "zod";

/**
 * How a value got into the knowledge base. Drives the provenance badge in the
 * review UI and determines whether a field can be trusted without checking.
 *
 * See docs/EDIT-UX.md §5 for the user-facing labels these map to.
 */
export const extractionMethodSchema = z.enum([
  "scraped", // copied from the page (JSON-LD, meta, or DOM)
  "derived", // computed from scraped content (palette, vendors, metrics)
  "ai-live", // generated by a real model call
  "ai-mock", // generated by the placeholder generator
  "user-edited", // set or corrected by a human in the review UI
  "not-found", // looked for, genuinely absent
]);

export type ExtractionMethod = z.infer<typeof extractionMethodSchema>;

/**
 * Wraps every value in the knowledge base with where it came from and how much
 * we trust it.
 *
 * This single envelope carries four features that would otherwise need separate
 * machinery: provenance badges, confidence-driven review triage, per-field
 * revert, and honest labelling of AI-generated content.
 *
 * `value: null` with `method: "not-found"` is a first-class state, not an error.
 * Roughly half of a typical scrape lands there (see docs/DATA-QUALITY.md §1).
 */
export function sourced<T extends z.ZodType>(value: T) {
  return z.object({
    value: value.nullable(),
    method: extractionMethodSchema,
    /** 0–1. Below 0.5 lands the field in the review UI's attention tier. */
    confidence: z.number().min(0).max(1),
    sourceUrls: z.array(z.string()),
    /** Free text for conflicts and caveats, e.g. two phone numbers found. */
    note: z.string().optional(),
  });
}

export type Sourced<T> = {
  value: T | null;
  method: ExtractionMethod;
  confidence: number;
  sourceUrls: string[];
  note?: string;
};

/** A value read directly off the page. */
export function scraped<T>(
  value: T,
  sourceUrl: string,
  confidence = 0.9,
): Sourced<T> {
  return { value, method: "scraped", confidence, sourceUrls: [sourceUrl] };
}

/** A value computed from scraped content rather than read from it. */
export function derived<T>(
  value: T,
  sourceUrls: string[],
  confidence = 0.7,
): Sourced<T> {
  return { value, method: "derived", confidence, sourceUrls };
}

/**
 * Looked for and genuinely absent. Extractors must return this rather than an
 * empty string or a plausible default — see docs/DATA-QUALITY.md §2.
 */
export function notFound<T>(note?: string): Sourced<T> {
  return {
    value: null,
    method: "not-found",
    confidence: 0,
    sourceUrls: [],
    ...(note ? { note } : {}),
  };
}

/**
 * Applies a user's correction. Always full confidence — the human is the
 * authority — and the original stays recoverable via the draft's `original`
 * snapshot rather than being kept here.
 */
export function userEdited<T>(value: T, previous?: Sourced<T>): Sourced<T> {
  return {
    value,
    method: "user-edited",
    confidence: 1,
    sourceUrls: previous?.sourceUrls ?? [],
  };
}

/** True when a field should surface in the review UI's attention tier. */
export function needsReview<T>(field: Sourced<T>): boolean {
  if (field.method === "user-edited") return false;
  if (field.method === "ai-live" || field.method === "ai-mock") return true;
  if (field.note !== undefined) return true; // conflict flagged by the reconciler
  return field.value !== null && field.confidence < 0.5;
}
